export const GET_BOARD_LIST = 'GET_BOARD_LIST'
export const GET_BOARD_LIST_SUCCESS = 'GET_BOARD_LIST_SUCCESS'
export const GET_BOARD_LIST_FAIL = 'GET_BOARD_LIST_FAIL'

export const CREATE_BOARD = 'CREATE_BOARD'
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS'
export const CREATE_BOARD_FAIL = 'CREATE_BOARD_FAIL'

export const UPDATE_BOARD_LIST = 'UPDATE_BOARD_LIST'
export const UPDATE_BOARD_LIST_SUCCESS = 'UPDATE_BOARD_LIST_SUCCESS'
export const UPDATE_BOARD_LIST_FAIL = 'UPDATE_BOARD_LIST_FAIL'